version: '3'
services:
  app:
    container_name: App
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  test:
    container_name: Test
    build:
      context: ./tests
      dockerfile: Dockerfile
    network_mode: service:app
    depends_on:
      - app
